# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vchimishuk/projects/loderunner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vchimishuk/projects/loderunner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vchimishuk/projects/loderunner/CMakeFiles /home/vchimishuk/projects/loderunner//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vchimishuk/projects/loderunner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named loderunner

# Build rule for target.
loderunner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loderunner
.PHONY : loderunner

# fast build rule for target.
loderunner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/build
.PHONY : loderunner/fast

exit.o: exit.c.o
.PHONY : exit.o

# target to build an object file
exit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/exit.c.o
.PHONY : exit.c.o

exit.i: exit.c.i
.PHONY : exit.i

# target to preprocess a source file
exit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/exit.c.i
.PHONY : exit.c.i

exit.s: exit.c.s
.PHONY : exit.s

# target to generate assembly for a file
exit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/exit.c.s
.PHONY : exit.c.s

game.o: game.c.o
.PHONY : game.o

# target to build an object file
game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/game.c.o
.PHONY : game.c.o

game.i: game.c.i
.PHONY : game.i

# target to preprocess a source file
game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/game.c.i
.PHONY : game.c.i

game.s: game.c.s
.PHONY : game.s

# target to generate assembly for a file
game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/game.c.s
.PHONY : game.c.s

level.o: level.c.o
.PHONY : level.o

# target to build an object file
level.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/level.c.o
.PHONY : level.c.o

level.i: level.c.i
.PHONY : level.i

# target to preprocess a source file
level.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/level.c.i
.PHONY : level.c.i

level.s: level.c.s
.PHONY : level.s

# target to generate assembly for a file
level.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/level.c.s
.PHONY : level.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/main.c.s
.PHONY : main.c.s

path.o: path.c.o
.PHONY : path.o

# target to build an object file
path.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/path.c.o
.PHONY : path.c.o

path.i: path.c.i
.PHONY : path.i

# target to preprocess a source file
path.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/path.c.i
.PHONY : path.c.i

path.s: path.c.s
.PHONY : path.s

# target to generate assembly for a file
path.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/path.c.s
.PHONY : path.c.s

render.o: render.c.o
.PHONY : render.o

# target to build an object file
render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/render.c.o
.PHONY : render.c.o

render.i: render.c.i
.PHONY : render.i

# target to preprocess a source file
render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/render.c.i
.PHONY : render.c.i

render.s: render.c.s
.PHONY : render.s

# target to generate assembly for a file
render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/render.c.s
.PHONY : render.c.s

runner.o: runner.c.o
.PHONY : runner.o

# target to build an object file
runner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/runner.c.o
.PHONY : runner.c.o

runner.i: runner.c.i
.PHONY : runner.i

# target to preprocess a source file
runner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/runner.c.i
.PHONY : runner.c.i

runner.s: runner.c.s
.PHONY : runner.s

# target to generate assembly for a file
runner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/runner.c.s
.PHONY : runner.c.s

texture.o: texture.c.o
.PHONY : texture.o

# target to build an object file
texture.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/texture.c.o
.PHONY : texture.c.o

texture.i: texture.c.i
.PHONY : texture.i

# target to preprocess a source file
texture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/texture.c.i
.PHONY : texture.c.i

texture.s: texture.c.s
.PHONY : texture.s

# target to generate assembly for a file
texture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/texture.c.s
.PHONY : texture.c.s

xmalloc.o: xmalloc.c.o
.PHONY : xmalloc.o

# target to build an object file
xmalloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/xmalloc.c.o
.PHONY : xmalloc.c.o

xmalloc.i: xmalloc.c.i
.PHONY : xmalloc.i

# target to preprocess a source file
xmalloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/xmalloc.c.i
.PHONY : xmalloc.c.i

xmalloc.s: xmalloc.c.s
.PHONY : xmalloc.s

# target to generate assembly for a file
xmalloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loderunner.dir/build.make CMakeFiles/loderunner.dir/xmalloc.c.s
.PHONY : xmalloc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... loderunner"
	@echo "... exit.o"
	@echo "... exit.i"
	@echo "... exit.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... level.o"
	@echo "... level.i"
	@echo "... level.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... path.o"
	@echo "... path.i"
	@echo "... path.s"
	@echo "... render.o"
	@echo "... render.i"
	@echo "... render.s"
	@echo "... runner.o"
	@echo "... runner.i"
	@echo "... runner.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
	@echo "... xmalloc.o"
	@echo "... xmalloc.i"
	@echo "... xmalloc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

